services:
  discount-service-mysql:
    container_name: discount-service_database
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_DATABASE: discount_service
    healthcheck:
      test: [ "CMD", "bash", "-c", "mysqladmin ping -u mysql -pmysql && mysql -u mysql -pmysql -e 'USE discount_service; SELECT 1'" ]
      start_period: 120s
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - all-services
  discount-service-app:
    container_name: discount-service_app
    image: discount-service:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://discount-service-mysql:3306/discount_service
      SPRING_DATASOURCE_USERNAME: mysql
      SPRING_DATASOURCE_PASSWORD: mysql
      USER_SERVICE_URL: http://user-service-app:8082
    depends_on:
      discount-service-mysql:
        condition: service_healthy
    networks:
      - all-services
networks:
  all-services:
    external: true