services:
  database:
    container_name: discount-service_database
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_DATABASE: discount_service
    healthcheck:
      test: [ "CMD", "bash", "-c", "mysqladmin ping -u mysql -pmysql && mysql -u mysql -pmysql -e 'USE discount_service; SELECT 1'" ]
      start_period: 120s
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
  app:
    container_name: discount-service_app
    image: discount-service:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/discount_service
      SPRING_DATASOURCE_USERNAME: mysql
      SPRING_DATASOURCE_PASSWORD: mysql
    depends_on:
      database:
        condition: service_healthy